name: Run Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - feature/*

jobs:
  test:
    name: Run test suite and upload coverage results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
        env: 
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - run: npm ci
      - run: npm test      
      - run: ./cc-test-reporter after-build --exit-code=$? -r=$CC_TEST_REPORTER_ID
